server:
  name: "elector-cab-svc"
  port: ":XXXX"
  base_path: "/api/v1"
  test_mode: true
  log:
    level: "debug"
    format: "text"

database:
  sql:
    url: "postgresql://postgres:postgres@db:XXXX/postgres?sslmode=disable"
  redis:
    addr: "localhost:7200"
    password: "example"
    db: 0
    lifetime: 15 #minutes

oauth:
  google:
    client_id: "client_id"
    client_secret: "megasupersecret"
    redirect_url: "http://localhost:XXXX/re-flow/v1/public/oauth/google/callback"

jwt:
  access_token:
    secret_key: "supersecretkey"
    token_lifetime: 900

kafka:
  brokers:
    - "re-news-kafka:XXXX"

swagger:
  enabled: true
  url: "/swagger"
  port: "XXXX"